version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - GOOS=linux go build hello_world.go

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - 'hello_world'
